remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Rebeca Canales
logo: /assets/img/profile_pic.jpg
description: Aspiring data scientist, passionate about business, technology, supply chain and the international arena. Currently finishing my Masters in Business Analytics
